//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;

namespace B2BAISERA.Models.EFServer
{
    public partial class EProcEntities : ObjectContext
    {
        public const string ConnectionString = "name=EProcEntities";
        public const string ContainerName = "EProcEntities";
    
        #region Constructors
    
        public EProcEntities()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public EProcEntities(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public EProcEntities(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<CUSTOM_DOWNLOAD_TRANSACTION> CUSTOM_DOWNLOAD_TRANSACTION
        {
            get { return _cUSTOM_DOWNLOAD_TRANSACTION  ?? (_cUSTOM_DOWNLOAD_TRANSACTION = CreateObjectSet<CUSTOM_DOWNLOAD_TRANSACTION>("CUSTOM_DOWNLOAD_TRANSACTION")); }
        }
        private ObjectSet<CUSTOM_DOWNLOAD_TRANSACTION> _cUSTOM_DOWNLOAD_TRANSACTION;
    
        public ObjectSet<CUSTOM_DOWNLOAD_TRANSACTIONDATA> CUSTOM_DOWNLOAD_TRANSACTIONDATA
        {
            get { return _cUSTOM_DOWNLOAD_TRANSACTIONDATA  ?? (_cUSTOM_DOWNLOAD_TRANSACTIONDATA = CreateObjectSet<CUSTOM_DOWNLOAD_TRANSACTIONDATA>("CUSTOM_DOWNLOAD_TRANSACTIONDATA")); }
        }
        private ObjectSet<CUSTOM_DOWNLOAD_TRANSACTIONDATA> _cUSTOM_DOWNLOAD_TRANSACTIONDATA;
    
        public ObjectSet<CUSTOM_DOWNLOAD_TRANSACTIONDATADETAIL> CUSTOM_DOWNLOAD_TRANSACTIONDATADETAIL
        {
            get { return _cUSTOM_DOWNLOAD_TRANSACTIONDATADETAIL  ?? (_cUSTOM_DOWNLOAD_TRANSACTIONDATADETAIL = CreateObjectSet<CUSTOM_DOWNLOAD_TRANSACTIONDATADETAIL>("CUSTOM_DOWNLOAD_TRANSACTIONDATADETAIL")); }
        }
        private ObjectSet<CUSTOM_DOWNLOAD_TRANSACTIONDATADETAIL> _cUSTOM_DOWNLOAD_TRANSACTIONDATADETAIL;
    
        public ObjectSet<CUSTOM_S02004> CUSTOM_S02004
        {
            get { return _cUSTOM_S02004  ?? (_cUSTOM_S02004 = CreateObjectSet<CUSTOM_S02004>("CUSTOM_S02004")); }
        }
        private ObjectSet<CUSTOM_S02004> _cUSTOM_S02004;
    
        public ObjectSet<CUSTOM_LOG> CUSTOM_LOG
        {
            get { return _cUSTOM_LOG  ?? (_cUSTOM_LOG = CreateObjectSet<CUSTOM_LOG>("CUSTOM_LOG")); }
        }
        private ObjectSet<CUSTOM_LOG> _cUSTOM_LOG;
    
        public ObjectSet<CUSTOM_USER> CUSTOM_USER
        {
            get { return _cUSTOM_USER  ?? (_cUSTOM_USER = CreateObjectSet<CUSTOM_USER>("CUSTOM_USER")); }
        }
        private ObjectSet<CUSTOM_USER> _cUSTOM_USER;

        #endregion
        #region Function Imports
        public ObjectResult<Nullable<int>> sp_UpdateS02004(string pONUMBER, Nullable<decimal> vERSIONPOSERA, Nullable<decimal> dATAVERSION, string sTATUS, string rEASONREJECTION)
        {
    
            ObjectParameter pONUMBERParameter;
    
            if (pONUMBER != null)
            {
                pONUMBERParameter = new ObjectParameter("PONUMBER", pONUMBER);
            }
            else
            {
                pONUMBERParameter = new ObjectParameter("PONUMBER", typeof(string));
            }
    
            ObjectParameter vERSIONPOSERAParameter;
    
            if (vERSIONPOSERA.HasValue)
            {
                vERSIONPOSERAParameter = new ObjectParameter("VERSIONPOSERA", vERSIONPOSERA);
            }
            else
            {
                vERSIONPOSERAParameter = new ObjectParameter("VERSIONPOSERA", typeof(decimal));
            }
    
            ObjectParameter dATAVERSIONParameter;
    
            if (dATAVERSION.HasValue)
            {
                dATAVERSIONParameter = new ObjectParameter("DATAVERSION", dATAVERSION);
            }
            else
            {
                dATAVERSIONParameter = new ObjectParameter("DATAVERSION", typeof(decimal));
            }
    
            ObjectParameter sTATUSParameter;
    
            if (sTATUS != null)
            {
                sTATUSParameter = new ObjectParameter("STATUS", sTATUS);
            }
            else
            {
                sTATUSParameter = new ObjectParameter("STATUS", typeof(string));
            }
    
            ObjectParameter rEASONREJECTIONParameter;
    
            if (rEASONREJECTION != null)
            {
                rEASONREJECTIONParameter = new ObjectParameter("REASONREJECTION", rEASONREJECTION);
            }
            else
            {
                rEASONREJECTIONParameter = new ObjectParameter("REASONREJECTION", typeof(string));
            }
            return base.ExecuteFunction<Nullable<int>>("sp_UpdateS02004", pONUMBERParameter, vERSIONPOSERAParameter, dATAVERSIONParameter, sTATUSParameter, rEASONREJECTIONParameter);
        }

        #endregion
    }
}
